language: minimal

env:
  global:
    - CONAN_USERNAME="khdkhd"
    - CONAN_CHANNEL="testing"
    - CONAN_ARCHS=x86_64
    - CONAN_LOGIN_USERNAME="nealrame"
    - CONAN_STABLE_BRANCH_PATTERN="release/*"
    - CONAN_UPLOAD_ONLY_WHEN_STABLE=1 # Will only upload when the branch matches "release/*"
    - CONAN_UPLOAD="https://api.bintray.com/conan/khdkhd/public-conan"
    - CONAN_REMOTES="https://api.bintray.com/conan/bincrafters/public-conan@True@bincrafters"

matrix:
  include:
    - os: linux
      language: python
      python: "3.7"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      dist: xenial
      env:
        - CONAN_GCC_VERSIONS=7
        - CC=gcc-7
        - CXX=g++-7

    - os: osx
      language: shell
      osx_image: xcode10.2
      env:
        - CONAN_APPLE_CLANG_VERSIONS=10.0

install:
  - chmod +x ./Scripts/CI/Travis/install.sh
  - ./Scripts/CI/Travis/install.sh

script:
  - chmod +x ./Scripts/CI/Travis/run.sh
  - ./Scripts/CI/Travis/run.sh
