language: python
python: "3.7"
env:
  global:
    - CONAN_USERNAME="khdkhd" # ADJUST WITH YOUR REFERENCE USERNAME!
    - CONAN_LOGIN_USERNAME="nealrame" # ADJUST WITH YOUR LOGIN USERNAME!
    - CONAN_CHANNEL="testing" # ADJUST WITH YOUR CHANNEL!
    - CONAN_UPLOAD="https://api.bintray.com/conan/khdkhd/public-conan"
    - CONAN_STABLE_BRANCH_PATTERN="release/*"
    - CONAN_UPLOAD_ONLY_WHEN_STABLE=1 # Will only upload when the branch matches "release/*"

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-6.0
            - george-edison55-precise-backports
          packages:
            - clang-6.0
            - cmake-data
            - cmake
      env:
        - MATRIX_EVAL="CONAN_CLANG_VERSIONS=6.0"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
          packages:
            - g++-7
            - cmake-data
            - cmake
      env:
        - MATRIX_EVAL="CONAN_GCC_VERSIONS=7"

before_install:
  - eval "${MATRIX_EVAL}"

install:
  - pip install conan --upgrade
  - pip install conan_package_tools

script:
  - chmod +x ./Scripts/CI/Travis/run.sh
  - ./Scripts/CI/Travis/run.sh
